// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAq_eDsJUhYRfsHeTKyY6TuRM128vYav3k',
    appId: '1:344916077169:web:4b4f5099f4cedfdb2409d0',
    messagingSenderId: '344916077169',
    projectId: 'happy-chat-29788',
    authDomain: 'happy-chat-29788.firebaseapp.com',
    storageBucket: 'happy-chat-29788.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9DJuNqWQMQ6TAG098sLTQ93ONBmqdq8M',
    appId: '1:344916077169:android:cd44c49152481dd22409d0',
    messagingSenderId: '344916077169',
    projectId: 'happy-chat-29788',
    storageBucket: 'happy-chat-29788.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACpw4P9eM_rk-IvFplF_Glgjo_pcVdgwI',
    appId: '1:344916077169:ios:35f92475fa3ba8cf2409d0',
    messagingSenderId: '344916077169',
    projectId: 'happy-chat-29788',
    storageBucket: 'happy-chat-29788.appspot.com',
    iosBundleId: 'com.example.happyChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACpw4P9eM_rk-IvFplF_Glgjo_pcVdgwI',
    appId: '1:344916077169:ios:d29a0d7695f631b52409d0',
    messagingSenderId: '344916077169',
    projectId: 'happy-chat-29788',
    storageBucket: 'happy-chat-29788.appspot.com',
    iosBundleId: 'com.example.happyChat.RunnerTests',
  );
}
